### ISSUE TITLE
Unknown element type specified!

### ISSUE THREAD

**Issue by vgvassilev** [fusiondirectory/fusiondirectory#18] opened 2016-05-29 15:39 UTC
I hit this when randomly browsing the contents (version 1.0.12).

After some debugging, this is the initial working state of the of filter::elements
```Array ( [FUNCTIONAL] => Array ( [type] => checkbox [tag] => FUNCTIONAL [default] => true [unset] => Array ( ) [set] => (!(|(objectClass=posixAccount))) ) [TEMPLATES] => Array ( [type] => checkbox [tag] => TEMPLATES [default] => Array ( ) [unset] => Array ( ) [set] => (objectClass=fdTemplate) ) [SAMBA] => Array ( [type] => checkbox [tag] => SAMBA [default] => true [unset] => [set] => ) [POSIX] => Array ( [type] => checkbox [tag] => POSIX [default] => true [unset] => Array ( ) [set] => (objectClass=posixAccount) ) [MAIL] => Array ( [type] => checkbox [tag] => MAIL [default] => true [unset] => [set] => ) [NAME] => Array ( [type] => textfield [tag] => NAME [size] => 20 [maxlength] => 60 [default] => Array ( ) [unset] => Array ( ) [set] => (|(cn=*$*)(sn=*$*)(givenName=*$*)(uid=*$*)(mail=*$*)) [alphabet] => true [autocomplete] => Array ( [backend] => LDAP [filter] => (&(objectClass=inetOrgPerson)(|(cn=*$NAME*)(sn=*$NAME*)(givenName=*$NAME*)(uid=*$NAME*)(mail=*$NAME*))) [attribute] => Array ( [0] => cn [1] => uid ) [frequency] => 0.5 [characters] => 3 ) ) )```

This is when I hit the error:
```
Array ( [WORKSTATION] => Array ( [type] => checkbox [tag] => WORKSTATION [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*W*) ) [APPLICATION] => Array ( [type] => checkbox [tag] => APPLICATION [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*A*) ) [TERMINAL] => Array ( [type] => checkbox [tag] => TERMINAL [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*T*) ) [UNKNOWN] => Array ( [type] => checkbox [tag] => UNKNOWN [default] => false [unset] => Array ( ) [set] => (gosaGroupObjects=*I*) ) [PRINTER] => Array ( [type] => checkbox [tag] => PRINTER [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*P*) ) [WINDOWS] => Array ( [type] => checkbox [tag] => WINDOWS [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*O*) ) [PRIMARY] => Array ( [type] => checkbox [tag] => PRIMARY [default] => true [unset] => Array ( ) [set] => (objectClass=posixGroup) ) [SERVER] => Array ( [type] => checkbox [tag] => SERVER [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*S*) ) [PHONE] => Array ( [type] => checkbox [tag] => PHONE [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*F*) ) [GROUP] => Array ( [type] => checkbox [tag] => GROUP [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*G*) ) [SAMBA] => Array ( [type] => checkbox [tag] => SAMBA [default] => true [unset] => [set] => ) [NAME] => Array ( [type] => textfield [tag] => NAME [size] => 20 [maxlength] => 60 [default] => Array ( ) [unset] => Array ( ) [set] => (|(cn=*$*)(description=*$*)) [alphabet] => true [autocomplete] => Array ( [backend] => LDAP [filter] => (&(|(objectClass=posixGroup)$ROLE(objectClass=groupOfNames))(|(cn=*$NAME*)(description=*$NAME*))) [attribute] => cn [frequency] => 0.5 [characters] => 3 ) ) [USER] => Array ( [type] => checkbox [tag] => USER [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*U*) ) [ROLE] => Array ( [type] => checkbox [tag] => ROLE [default] => true [unset] => Array ( ) [set] => (objectClass=organizationalRole) ) [MAIL] => Array ( [type] => checkbox [tag] => MAIL [default] => true [unset] => [set] => ) [FUNCTIONAL] => Array ( [set] => (!(|(objectClass=posixAccount))) ) ) Array ( [WORKSTATION] => Array ( [type] => checkbox [tag] => WORKSTATION [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*W*) ) [APPLICATION] => Array ( [type] => checkbox [tag] => APPLICATION [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*A*) ) [TERMINAL] => Array ( [type] => checkbox [tag] => TERMINAL [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*T*) ) [UNKNOWN] => Array ( [type] => checkbox [tag] => UNKNOWN [default] => false [unset] => Array ( ) [set] => (gosaGroupObjects=*I*) ) [PRINTER] => Array ( [type] => checkbox [tag] => PRINTER [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*P*) ) [WINDOWS] => Array ( [type] => checkbox [tag] => WINDOWS [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*O*) ) [PRIMARY] => Array ( [type] => checkbox [tag] => PRIMARY [default] => true [unset] => Array ( ) [set] => (objectClass=posixGroup) ) [SERVER] => Array ( [type] => checkbox [tag] => SERVER [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*S*) ) [PHONE] => Array ( [type] => checkbox [tag] => PHONE [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*F*) ) [GROUP] => Array ( [type] => checkbox [tag] => GROUP [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*G*) ) [SAMBA] => Array ( [type] => checkbox [tag] => SAMBA [default] => true [unset] => [set] => ) [NAME] => Array ( [type] => textfield [tag] => NAME [size] => 20 [maxlength] => 60 [default] => Array ( ) [unset] => Array ( ) [set] => (|(cn=*$*)(description=*$*)) [alphabet] => true [autocomplete] => Array ( [backend] => LDAP [filter] => (&(|(objectClass=posixGroup)$ROLE(objectClass=groupOfNames))(|(cn=*$NAME*)(description=*$NAME*))) [attribute] => cn [frequency] => 0.5 [characters] => 3 ) ) [USER] => Array ( [type] => checkbox [tag] => USER [default] => true [unset] => Array ( ) [set] => (gosaGroupObjects=*U*) ) [ROLE] => Array ( [type] => checkbox [tag] => ROLE [default] => true [unset] => Array ( ) [set] => (objectClass=organizationalRole) ) [MAIL] => Array ( [type] => checkbox [tag] => MAIL [default] => true [unset] => [set] => ) [FUNCTIONAL] => Array ( [set] => (!(|(objectClass=posixAccount))) ) ) Unknown element type specified! FUNCTIONAL
```
It seems that it keeps piling up things. If I logout and login it works again.

**Comment by bilbo-the-hobbit** [comment] 2016-05-29 17:23
hello,

can you tell us on which distribution and on which php version

Cheers

**Comment by vgvassilev** [comment] 2016-05-29 17:36
`php -v`
PHP 7.0.7-2+donate.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

`cat /etc/lsb-release` 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

**Comment by bilbo-the-hobbit** [comment] 2016-05-29 17:42
ok seems this is another problem php7 related, you can try the fixes version who has already lots of php7 fixes here 

http://integration.opensides.be/repos/fixes-releases/debian/fusiondirectory-112-fixes-jessie/

to see if the problem still persist, beware that its not a released version

Cheers

**Comment by vgvassilev** [comment] 2016-05-29 17:48
Hm, how I can use this through apt-get? Also I see that in the dependencies of fusiondirectory there is  php7. I tried with php5.6 and got all sorts of issues, too.

**Comment by bilbo-the-hobbit** [comment] 2016-05-29 17:51
FusionDirectory work perfectly under php 5.4 until 5.6 ubuntu 16 is php7 as it seems. to use this just use 

deb http://integration.opensides.be/repos/fixes-releases/debian/fusiondirectory-112-fixes-jessie/ jessie/main

Cheers

**Comment by bilbo-the-hobbit** [comment] 2016-06-02 09:38
Hello,

the version in fixes as most of the issues about php7 corrected, and i have played with the filters and cannot reproduce anymore in the users and groups selections filters

so i will close it reopen if the fixes version still have the issues.

you will need smarty 3.1.29 and smarty-gettext 1.3.0 for fusiondirectory to work correctly

Cheers

**Closed by bilbo-the-hobbit** 2016-06-02 09:38 UTC

**Comment by vgvassilev** [comment] 2016-06-27 08:58
I confirm that installing smarty 3.1.29 and smarty-gettext 1.3.0 fixes the issue. They are currently available via deb http://ftp.de.debian.org/debian experimental main.

We updated the fusiondirectory to 1.0.13-1.

**Comment by DeMiNe0** [comment] 2017-02-08 18:02
Sorry, but how do you actually use these repo's? I'm on Ubuntu 16.04 and fusiondirectory is unusable with this issue. I've added the repo's so my sources lists but I can't find valid gpg keys for them. I also don't know how to make ubuntu use these repo's over the original.

**Comment by MCMic** [comment] 2017-02-09 08:11
Seems to be the same as https://github.com/fusiondirectory/fusiondirectory/issues/34
Please comment there. The repo mentionned here is too old.
